services:
  postgres:
    container_name: investment_risk_analysis_db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=risk_engine
    ports:
      - "5432:5432"
