FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /portfolio ./cmd/portfolio

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
COPY --from=builder /portfolio /portfolio
EXPOSE 8082
ENTRYPOINT ["/portfolio"]
